// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.JDriveTrain;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon drivetrainLeftDriveLead;
    public static CANTalon drivetrainLeftDriveFollow;
    public static CANTalon drivetrainRightDriveLead;
    public static CANTalon drivetrainRightDriveFollow;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainLeftDriveLead = new CANTalon(6);
        LiveWindow.addActuator("Drivetrain", "LeftDriveLead", drivetrainLeftDriveLead);
        
        drivetrainLeftDriveFollow = new CANTalon(5);
        LiveWindow.addActuator("Drivetrain", "LeftDriveFollow", drivetrainLeftDriveFollow);
        
        drivetrainRightDriveLead = new CANTalon(4);
        LiveWindow.addActuator("Drivetrain", "RightDriveLead", drivetrainRightDriveLead);
        
        drivetrainRightDriveFollow = new CANTalon(3);
        LiveWindow.addActuator("Drivetrain", "RightDriveFollow", drivetrainRightDriveFollow);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
